### ISSUE TITLE
The Collision Stats only show a half

### ISSUE THREAD

**Issue by sahdsg** [AnkiUniversal/Anki-Universal#13]
![wp_ss_20170808_0002](https://user-images.githubusercontent.com/17263703/29079961-25bfdf80-7c91-11e7-92e9-90e479aaeb1e.png)
Hi
the upper part can't be seen..

**Comment by AnkiUniversal** [comment]
Hi, you can scroll the charts up by swiping up.

**Comment by sahdsg** [comment]
![20170809085457](https://user-images.githubusercontent.com/17263703/29101016-29b66d2e-7ce2-11e7-9aca-6f1cef4fd75a.jpg)
sorry for misleading..

**Comment by AnkiUniversal** [comment]
Hi, I understand the problem now. The line and bar charts are not rendered correctly. Seem like the plotting API (OxyPlot v1.0) has some serious bugs. We will update this API as soon as their newest stable version (v2.0) is released.

Thank you for informing us about this.
