### ISSUE TITLE
Ink color in night mode

### ISSUE THREAD

**Issue by Ghabry** [AnkiUniversal/Anki-Universal#15]
I use the handwriting setting to draw & recall Kanjis. Really awesome that the app supports a whiteboard feature like the Android app. Was always really tedious when using normal Anki Desktop.

I only have one minor visual problem: When the night mode is the ink is still blue and quite hard to see. Could you change the ink color to have better contrast during night mode?

Thanks!

**Comment by AnkiUniversal** [comment]
Hi, we'll use a lighter color for ink in night mode in the next update.

**Comment by Ghabry** [comment]
Much better. Thanks for the quick fix 👍
