### ISSUE TITLE
Enhancement requests

### ISSUE THREAD

**Issue by sliNO** [AnkiUniversal/Anki-Universal#16]
Hi, I really like the app but I wanted to ask for some small enahncements:

1. Make it possible to temporarly concat real decks into "virtual" decks. 
For example: I have a deck for biology and one for economics. For test preparation i would love to be able to create a virtual deck from which I get the cards of biology and economics shown in a mixed order.

2. Make it possible to set the background color of the night mode to real black - this saves up to 20% battery for an OLED-display

3. Add a "Don't show again" option for the dialog which pops up if you change the card type - it is a bit
annoying. Other solution: Dont show this dialog at all if there are no inputs at all till now.

Thanks in advance and keep up the god work 🥇
PS: I am familar with c#, so i could probably participate some these points, if there is a demand for it.

**Comment by AnkiUniversal** [comment]
Hi,
1. To create a deck like that you can use parent-child decks & custom study:
   a. Please create a new deck named "Concat" (or anything you like.)
   b. Then choose "Drag Decks" on the top bar and drag your decks (biology & economics) onto the new deck. Please choose "Drag Decks" again after you've finished.
   c. On the new deck choose "Deck menu\Custom Study". A new pop-up will appear.
   d. Please choose "All cards in random order" and type in the number of cards you want to study (or just hold "9" to auto get the max number of cards. This will guarantee all child decks are included.)
   e. A new "Custom Study" deck will be created. This deck will have random cards from all "Concat" child decks in a random order. You can learn by using this deck. Please note that this deck will disappear once you have viewed all of its cards.

2. This is an interesting suggestion. Though I think we only need to implement this for learning/reviewing cards. Other pages like _Settings, Options, Note Editor,..._ don't have high usage and some of their UI parts are already black. However, card viewer uses javascript, html, and CSS to set the color ( which is done by another member) so I don't know if we can implement this. 

3.  This seems like a bug. If there is no inputs the warning message should not appear at all. We'll fix this in the next update. 

Best regards,
Anki Universal Team

**Comment by sliNO** [comment]
Ty very much for your answer.
It is awsome that there is already a way to concat decks 👍 

For point 2 you are are right, it would only be useful within the learning/review cards section.

Best regards,
sliNO
