### ISSUE TITLE
Make Anki remember whether card piles are folded or unfolded.

### ISSUE THREAD

**Issue by soerendip** [AnkiUniversal/Anki-Universal#20]
Hi, 
great work, thanks for coding this!
Every time I come to the view with the card decks, all decks are unfolded. It means, all subdecks that are part of a parent deck are visible. I have to press the little triangle symbol to fold it. When the decks are unfolded the view becomes very messy. And I have to fold the decks each single time coming back to the decks view. I wonder whether it would not be more useful to make anki remember the state until the user changes it again. It should be an easy change in code.

**Comment by AnkiUniversal** [comment]
Hi, when we started to support sub-decks, we really wanted to make folding as the default action. However, this would create a render problem that left white spaces between parent decks when opening the app.

I did some checks and this bug had been fixed. So in the next update, folding will be the default action when viewing decks as a list.
