### ISSUE TITLE
Anki in nightmode as standard?

### ISSUE THREAD

**Issue by soerendip** [AnkiUniversal/Anki-Universal#21]
Would it be possible to add an option in the settings so that Anki opens in night mode by default.
regards
Sören

**Comment by AnkiUniversal** [comment]
Hi, night/day mode is auto-saved. After you have switched to night mode, it'll stay that way until you change back to day mode manually.

**Comment by soerendip** [comment]
Oh, great. For some reason it was switched back to day mode. And I thought Anki sets it back to day mode each time. Thanks.
