### ISSUE TITLE
Missing a view that displays all cards in a deck at once.

### ISSUE THREAD

**Issue by soerendip** [AnkiUniversal/Anki-Universal#22]
Would be nice to have like on AnkiDroid. A view that lists all current cards with front and back. So you can directly search and jump to a certain card. A simple table with two columns would do it.

**Comment by AnkiUniversal** [comment]
Hi, to do this please click on "Deck Menu" (latest version) or right click on your deck and choose "Search cards".

**Comment by soerendip** [comment]
All right.  For some reason it was switched back to day mode. Probably, I did that and forgot about it. Great!

**Comment by soerendip** [comment]
Great!
