### ISSUE TITLE
Smart lists or "decks" by tags

### ISSUE THREAD

**Issue by soerendip** [AnkiUniversal/Anki-Universal#23]
It would be great to have "smart lists" that are generated from the tags in a card. I am not familiar all possibilities in  Anki, but at the moment, it seems the tags are rather useless. So, one idea, is to auto-generate decks by tags. By that we could learn with a certain focus. E.g. the user has a deck math and within it cards with tags Algebra, Analysis, Vectorspace etc. By default the user gets all cards from the deck, but when using the smart list s/he would get only cards from Algebra.

By that a card that is relevant for multiple fields would appear in multiple lists. This would be superior to using subdecks where all cards are fixed to a certain deck.

**Comment by AnkiUniversal** [comment]
Hi, to do this please click on "Deck menu" (or right click) on your deck then choose "Custom Study".

On the new pop-up, please choose "All cards in random order". This option will allow you to create a custom study deck that limits to chosen tags.

**Comment by soerendip** [comment]
Ok, and are the cards removed from the original deck? Cause when I remove the Custom Study it says "all cards will return to the original deck.
