### ISSUE TITLE
Change card font

### ISSUE THREAD

**Issue by NataKun** [AnkiUniversal/Anki-Universal#28]
Hi, I have a deck of Kanji that I changed the font on with the Windows ver. of Anki. The font syncs when I use Anki Droid or the PC ver. or on Anki web, but in Anki Universal, it shows the default font. Is there a way to have it sync with my custom font? Thanks!

![ankinetfont](https://user-images.githubusercontent.com/10178654/37798334-d231b47e-2df2-11e8-8ee3-169c883edb4b.PNG)
![ankiunifont](https://user-images.githubusercontent.com/10178654/37798335-d2440a02-2df2-11e8-9f2f-89f25038b718.PNG)

**Comment by NataKun** [comment]
Ah I see. Ill do that then. Thanks for the reply!

**Comment by NataKun** [comment]
Hey! So I installed my font to C:\Windows\Fonts, but I cant get AnkiUniversal to use those fonts. Is there a way to have the app use those font (maybe only for the Kanji) without having to change my system wide font? Thanks.

**Comment by AnkiUniversal** [comment]
Hi, another way is to add the font into your collection.media folder if you have newest version of Anki Universal (>= 1.4.9.0, you can see the version by selecting "Feedback" from the menu). 

Firstly, exporting your decks which have the custom font from either AnkiDroid or the classic PC app (remember to choose "Include Media Files").
Then on Anki Universal, please select "Insert Media Files". On the new pop-up, choose your deck then and select the exported package. The font should be imported successfully.

**Comment by NataKun** [comment]
I tried doing what you said, but it doesn't seem to work. It still shows me the default font :/
I tried a few times and rebooted...

I attached pics of edits I did to the cards to get the custom font If it helps

![capture](https://user-images.githubusercontent.com/10178654/38049196-919cac32-3295-11e8-9553-308fbd1c09db.PNG)
![capture1](https://user-images.githubusercontent.com/10178654/38049197-91b45062-3295-11e8-807e-82139d88048a.PNG)

**Comment by AnkiUniversal** [comment]
Hi, it's best if you can send us the deck with custom font so we can try to locate the problem.

**Comment by NataKun** [comment]
[Heisig's Remember the Kanji (RTK) 1+3.zip](https://github.com/AnkiUniversal/Anki-Universal/files/1858461/Heisig.s.Remember.the.Kanji.RTK.1.3.zip)

**Comment by AnkiUniversal** [comment]
Hi, I found the problem. Since Anki Universal uses HTML5 format, you'll need to put **class="kanji"** in your span tag on the front template like this:
```
<div><span class="kanji">{{Kanji}}</span><br></div>
<div style='font-family: Arial; font-size: 20px;'>{{On-yomi}}</div>
```

This will make sure the font work on both Anki Universal and other versions.

**Comment by NataKun** [comment]
Thank you so much! It worked!!!
