### ISSUE TITLE
problem about LaTeX and cloze

### ISSUE THREAD

**Issue by wintercicada-xyz** [AnkiUniversal/Anki-Universal#37]
It seems that LaTeX cannot work with cloze，I try [$]{{c1:: latex}}[/$] and {{c1::[$] latex [/$]}},but both of them just displayed the original text ,is that I use them in the wrong way or it is a bug?

**Comment by AnkiUniversal** [comment]
The second method: {{c1::[$] latex [/$]}} should work like expected, for
example:

*Note editor:*
[image: 1.PNG]

*Question:*
[image: 2.PNG]

*Answer:*
[image: 3.PNG]

**Comment by wintercicada-xyz** [comment]
I try it again,and it works!Thanks for your reply.
